### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by codetheweb**

### CODE REVIEW

**Comment by codetheweb** [comment]
@cloudybyte thanks for the help!

It's building now but not working (seems like data is being written to the sink but not read), if you have a chance to take a look I'd really appreciate it. :)

**Comment by cloudybyte** [comment]
uuuh that would take me at least till friday... Adding unit tests would help preventing that I guess

**Comment by codetheweb** [comment]
No rush, I started it so don't feel obligated.

Integration tests would be nice but I think would be quite hard to create since we'd either have to fake a Discord API server or test against the live Discord API and somehow click through the Spotify and Discord client GUIs.

**Comment by cloudybyte** [comment]
I don't think faking external services would be worth the effort... We could start with just having unit tests and testing our own functions as serenity and other dependencies likely have their own

**Comment by codetheweb** [comment]
I was able to get it working; needed to change the gateway intents.

> I don't think faking external services would be worth the effort... We could start with just having unit tests and testing our own functions as serenity and other dependencies likely have their own

I'd love to see this, I'm just not sure how valuable it would be since Aoede is so tightly integrated with librespot/serenity/songbird.

**Pull request merged**
